//created on: Jun 14, 2018
package drools.spring.rules

import rs.uns.ac.ftn.cdss.dto.SymptomDto;
import rs.uns.ac.ftn.cdss.dto.Symptoms;


rule "Your 2 Rule"

    when
        //conditions
    then
        System.out.println("Doktor Zarko Drageljevic, pravilo 2");
end

rule "Your 3 Rule"

    when
        //conditions
    then
        System.out.println("Doktor Zarko Drageljevic, pravilo 3");
end